name: auto-build

on:
  schedule:
    # At minute 0 on every day-of-week from Monday through Friday.
    # Thanks https://crontab.guru/
    - cron: '0 * * * MON-FRI'

jobs:
  auto-build:
    environment: auto-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: check for new osc-api version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
