name: auto-build-v1

on:
  schedule:
    # At 12:00 on every day-of-week from Monday through Friday.
    # thanks https://crontab.guru/
    - cron: '0 12 * * 1-5'

jobs:
  auto-build:
    environment: auto-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: check for new osc-api version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: make osc-api-check
      - name: check for release duplicate
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: make release-check-duplicate
      - name: auto-generate release
        run: make release-build
      - name: push release branch
        run: make release-push
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: create pull request
        run: make release-pr
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
