name: CI

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    environment: eu-west-2

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Reuse specification test
        run: make reuse-test
      - name: SDK re-generation test
        run: make regen-test
      - name: Go tests
        env:
          OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
          OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
        run: make go-test
